In [19]:
import pandas as pd
import numpy as np
import requests

In [20]:
# Get and Transform data from Wikipedia page dataframe
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
page=requests.get(url).text
df1= pd.read_html(page, header=0, attrs={"class":"wikitable sortable"})[0]
df1.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [21]:
# Group by  postcode and Borough and create new dataframe
df2=df1.groupby(['Postcode','Borough'],sort=False).agg(lambda x: ','.join(x))
df2.reset_index(level=['Postcode','Borough'], inplace=True) 
df2.rename(columns={'Postcode':'PostalCode','Neighbourhood':'Neighborhood'}, inplace=True)
df2.head(15)

   PostalCode           Borough                     Neighborhood
0         M1A      Not assigned                     Not assigned
1         M2A      Not assigned                     Not assigned
2         M3A        North York                        Parkwoods
3         M4A        North York                 Victoria Village
4         M5A  Downtown Toronto         Harbourfront,Regent Park
5         M6A        North York  Lawrence Heights,Lawrence Manor
6         M7A      Queen's Park                     Not assigned
7         M8A      Not assigned                     Not assigned
8         M9A         Etobicoke                 Islington Avenue
9         M1B       Scarborough                    Rouge,Malvern
10        M2B      Not assigned                     Not assigned
11        M3B        North York                  Don Mills North
12        M4B         East York   Woodbine Gardens,Parkview Hill
13        M5B  Downtown Toronto          Ryerson,Garden District
14        M6B        North York                        Glencairn

In [22]:
# If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough
df2.loc[df2['Neighborhood']=="Not assigned",'Neighborhood']=df2.loc[df2['Neighborhood']=="Not assigned",'Borough']
df2.head(15)

   PostalCode           Borough                     Neighborhood
0         M1A      Not assigned                     Not assigned
1         M2A      Not assigned                     Not assigned
2         M3A        North York                        Parkwoods
3         M4A        North York                 Victoria Village
4         M5A  Downtown Toronto         Harbourfront,Regent Park
5         M6A        North York  Lawrence Heights,Lawrence Manor
6         M7A      Queen's Park                     Queen's Park
7         M8A      Not assigned                     Not assigned
8         M9A         Etobicoke                 Islington Avenue
9         M1B       Scarborough                    Rouge,Malvern
10        M2B      Not assigned                     Not assigned
11        M3B        North York                  Don Mills North
12        M4B         East York   Woodbine Gardens,Parkview Hill
13        M5B  Downtown Toronto          Ryerson,Garden District
14        M6B        North York                        Glencairn

In [23]:
#  Ignore cells in "borough" that is "Not assigned"
df2.replace("Not assigned", np.nan, inplace=True)
df2.dropna(subset=["Borough"],axis=0, inplace=True)
df2.reset_index(drop=True, inplace=True)
df2.head(15)

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Harbourfront,Regent Park"
3,M6A,North York,"Lawrence Heights,Lawrence Manor"
4,M7A,Queen's Park,Queen's Park
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Rouge,Malvern"
7,M3B,North York,Don Mills North
8,M4B,East York,"Woodbine Gardens,Parkview Hill"
9,M5B,Downtown Toronto,"Ryerson,Garden District"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"Cloverdale,Islington,Martin Grove,Princess Gar..."
12,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union"
13,M3C,North York,"Flemingdon Park,Don Mills South"
14,M4C,East York,Woodbine Heights

In [26]:
df2.shape

(103, 3)